### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by WaseemRehman92** [guzhaoyuan/epos2#2]
Hi,

I have compiled the code for Maxon Motor Wrapper and constantly getting the following error:

/home/user/EPOSC_ws/src/MaxonEpos2/src/controller3.cpp:10:43: fatal error: epos2/Torque2.h: No such file or directory
#include "epos2/Torque2.h" // service file
compilation terminated.
/home/user/EPOSC_ws/src/MaxonEpos2/src/controller2.cpp:10:42: fatal error: epos2/Torque.h: No such file or directory
#include "epos2/Torque.h" // service file

Could you suggest any resolution to this error? I couldn't find Torque.h, Torque2.h files in the code repository.

Regards,

**Comment by guzhaoyuan** [comment]
Hey, the Torque.h, Torque2.h are ROS generated service files. If you compile the project with ROS catkin_make, you don't need to worry about these headers. 
Also, I have created a repo with cleaner code and explanation [here](https://github.com/guzhaoyuan/MaxonEpos2). Please check it out there. This is a messy repository for specific application.
